// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-donors.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-donors.ts
var list_donors_default = defineTool({
  name: "list_donors",
  title: "List donors",
  description: "List or search campus donors by name, phone or address. Optionally filter by cluster name.",
  inputSchema: {
    search: z.string().optional().describe("Text to match against donor name, phone or address."),
    cluster: z.string().optional().describe("Cluster name to filter by."),
    limit: z.number().int().optional().describe("Maximum number of donors to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, cluster, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("donors").select("id, name, phone, address, location, clusters(name), sub_clusters(name)").order("name").limit(Math.min(Math.max(limit ?? 25, 1), 200));
    if (search) {
      const term = search.replace(/[%,]/g, " ").trim();
      query = query.or(`name.ilike.%${term}%,phone.ilike.%${term}%,address.ilike.%${term}%`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((d) => ({
      id: d.id,
      name: d.name,
      phone: d.phone ?? null,
      address: d.address ?? null,
      cluster: d.clusters?.name ?? null,
      sub_cluster: d.sub_clusters?.name ?? null
    })).filter((d) => !cluster || (d.cluster ?? "").toLowerCase().includes(cluster.toLowerCase()));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { donors: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get-donor.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_donor_default = defineTool2({
  name: "get_donor",
  title: "Get donor details",
  description: "Get one donor's profile together with their donation history and total contributed.",
  inputSchema: {
    donor_id: z2.string().describe("The donor id returned by list_donors.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ donor_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: donor, error } = await supabase.from("donors").select("id, name, phone, address, location, notes, clusters(name), sub_clusters(name)").eq("id", donor_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!donor) return { content: [{ type: "text", text: "Donor not found" }], isError: true };
    const { data: donations, error: donationsError } = await supabase.from("donations").select("id, amount, donation_date, receipt_number, notes").eq("donor_id", donor_id).order("donation_date", { ascending: false });
    if (donationsError) {
      return { content: [{ type: "text", text: donationsError.message }], isError: true };
    }
    const total = (donations ?? []).reduce((sum, d) => sum + Number(d.amount ?? 0), 0);
    const payload = { donor, donations: donations ?? [], total_amount: total };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-donations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_donations_default = defineTool3({
  name: "list_donations",
  title: "List donations",
  description: "List donations in a date range, newest first, with donor names, receipt numbers and the total for the range.",
  inputSchema: {
    from_date: z3.string().optional().describe("Start date, inclusive, as YYYY-MM-DD."),
    to_date: z3.string().optional().describe("End date, inclusive, as YYYY-MM-DD."),
    limit: z3.number().int().optional().describe("Maximum number of donations to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("donations").select("id, amount, donation_date, receipt_number, notes, donors(name, phone)").order("donation_date", { ascending: false }).limit(Math.min(Math.max(limit ?? 50, 1), 500));
    if (from_date) query = query.gte("donation_date", from_date);
    if (to_date) query = query.lte("donation_date", to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((d) => ({
      id: d.id,
      date: d.donation_date,
      amount: Number(d.amount ?? 0),
      receipt_number: d.receipt_number ?? null,
      donor: d.donors?.name ?? null,
      notes: d.notes ?? null
    }));
    const total = rows.reduce((sum, r) => sum + r.amount, 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ donations: rows, total }, null, 2) }],
      structuredContent: { donations: rows, total, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/record-donation.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var record_donation_default = defineTool4({
  name: "record_donation",
  title: "Record a donation",
  description: "Record a new donation for an existing donor. Use list_donors first to find the donor id.",
  inputSchema: {
    donor_id: z4.string().describe("The donor id the donation belongs to."),
    amount: z4.number().describe("Donation amount in rupees."),
    donation_date: z4.string().optional().describe("Donation date as YYYY-MM-DD. Defaults to today."),
    receipt_number: z4.string().optional().describe("Receipt number, if one was issued."),
    notes: z4.string().optional().describe("Optional note about the donation.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ donor_id, amount, donation_date, receipt_number, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!(amount > 0)) {
      return { content: [{ type: "text", text: "Amount must be greater than zero" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("donations").insert({
      donor_id,
      amount,
      donation_date: donation_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      receipt_number: receipt_number ?? null,
      notes: notes ?? null
    }).select("id, amount, donation_date, receipt_number").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { donation: data }
    };
  }
});

// src/lib/mcp/tools/list-clusters.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_clusters_default = defineTool5({
  name: "list_clusters",
  title: "List clusters",
  description: "List all donor clusters and their sub-clusters.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("clusters").select("id, name, sort_order, sub_clusters(id, name)").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clusters: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-dua-requests.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_dua_requests_default = defineTool6({
  name: "list_dua_requests",
  title: "List dua requests",
  description: "List prayer (dua) requests submitted by donors, newest first.",
  inputSchema: {
    status: z5.string().optional().describe("Filter by status, e.g. pending or replied."),
    limit: z5.number().int().optional().describe("Maximum number of requests to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("dua_requests").select("*").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 25, 1), 200));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { requests: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sdbescoppznbzwuhdnap";
var mcp_default = defineMcp({
  name: "ajmeer-gate-campus-karad",
  title: "Ajmeer Gate Campus Karad",
  version: "0.1.0",
  instructions: "Tools for the Ajmeer Gate Campus Karad donation system. Search donors, read donation history and reports, record new donations, list clusters, and review dua (prayer) requests. Always find a donor with list_donors before recording a donation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_donors_default, get_donor_default, list_donations_default, record_donation_default, list_clusters_default, list_dua_requests_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
